anekdots:
  list:
    - Dyslexic man walks into a bra
    - I'm on a whiskey diet. I've lost three days already.
    - I went to buy some camouflage trousers the other day but I couldn't find any.
    - Slept like a log last night... Woke up in the fireplace.
    - A sandwich walks into a bar. The barman says "Sorry we don't serve food in here"
    - I tried water polo but my horse drowned.
